name: docs

on:
  # trigger deployment on every push to main branch
  push:
    branches: [main]

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          # fetch all commits to get last updated time or other git log info
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          # choose node.js version to use
          node-version: "16"

      - name: Cache pnpm modules
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnp

      - name: Setup PNPM
        # You may pin to the exact commit or the version.
        # uses: pnpm/action-setup@646cdf48217256a3d0b80361c5a50727664284f2
        uses: pnpm/action-setup@v2.0.1
        with:
          # Version of PNPM to install
          version: 6.24.2
          # Where to store PNPM files
          # If specified, run `pnpm install`
          run_install: true # optional, default is null

      # run build script
      - name: Build VuePress site
        run: pnpm build:docs

      # please check out the docs of the workflow for more details
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          # deploy to gh-pages branch
          target_branch: gh-pages
          # deploy the default output dir of VuePress
          build_dir: packages/site/docs/.vuepress/dist
        env:
          # @see https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
